import { StyleSheet, Dimensions, Platform } from 'react-native';

const { width, height } = Dimensions.get('window');

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: 'white',
    },
    mapContainer: {
        ...StyleSheet.absoluteFillObject,
    },
    map: {
        ...StyleSheet.absoluteFillObject,
    },
    bottomContainer: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        zIndex: 2,
    },
    bottomCard: {
        backgroundColor: 'white',
        borderTopLeftRadius: 20,
        borderTopRightRadius: 20,
        padding: 20,
        paddingBottom: Platform.OS === 'ios' ? 40 : 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: -2 },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
    },
    statsContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 20,
        paddingHorizontal: 10,
    },
    statItem: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
    },
    statValue: {
        fontSize: 24,
        color: '#33A001',
        fontWeight: '600',
        textAlign: 'center',
    },
    statLabel: {
        fontSize: 14,
        color: '#666',
        marginTop: 4,
        textAlign: 'center',
    },
    endRunButton: {
        backgroundColor: '#33A001',
        borderRadius: 30,
        padding: 15,
        marginHorizontal: 10,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
    },
    endRunText: {
        color: 'white',
        fontSize: 24,
        fontWeight: 'bold',
        textAlign: 'center',
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    modalContent: {
        backgroundColor: 'white',
        borderRadius: 20,
        padding: 25,
        width: width * 0.85,
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
    },
    modalText: {
        fontSize: 20,
        fontWeight: '600',
        textAlign: 'center',
        marginBottom: 25,
        color: '#333',
    },
    modalButtons: {
        width: '100%',
        flexDirection: 'column',
        gap: 10,
    },
    modalButton: {
        width: '100%',
        padding: 15,
        borderRadius: 30,
        alignItems: 'center',
        justifyContent: 'center',
    },
    modalButtonPrimary: {
        backgroundColor: '#33A001',
    },
    modalButtonSecondary: {
        backgroundColor: 'white',
        borderWidth: 2,
        borderColor: '#33A001',
    },
    modalButtonText: {
        fontSize: 18,
        fontWeight: '600',
        color: 'white',
    },
    modalButtonTextSecondary: {
        color: '#33A001',
    },
    loadingOverlay: {
        ...StyleSheet.absoluteFillObject,
        backgroundColor: 'rgba(255, 255, 255, 0.95)',
        justifyContent: 'center',
        alignItems: 'center',
        zIndex: 3,
    },
    loadingText: {
        marginTop: 20,
        fontSize: 18,
        color: '#33A001',
        fontWeight: '600',
    },
    loadingSubText: {
        marginTop: 10,
        fontSize: 14,
        color: '#666',
        textAlign: 'center',
        paddingHorizontal: 40,
    },
    errorOverlay: {
        ...StyleSheet.absoluteFillObject,
        backgroundColor: 'rgba(255, 255, 255, 0.95)',
        justifyContent: 'center',
        alignItems: 'center',
        zIndex: 3,
        padding: 20,
    },
    errorText: {
        fontSize: 16,
        color: '#FF3B30',
        textAlign: 'center',
        marginBottom: 20,
    },
    retryButton: {
        backgroundColor: '#33A001',
        paddingVertical: 12,
        paddingHorizontal: 30,
        borderRadius: 25,
    },
    retryButtonText: {
        color: 'white',
        fontSize: 16,
        fontWeight: '600',
    },
    instructionContainer: {
        position: 'absolute',
        height: 100,
        width: 432,
        left: -5,
        right: 0,
        zIndex: 2,
        paddingHorizontal: 20,
    },
    instructionCard: {
        backgroundColor: 'white',
        height: 100,
        left: -15,
        borderRadius: 15,
        padding: 10,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
    },
    instructionText: {
        paddingTop: 35,
        fontSize: 25,
        textAlign: 'center',
        color: '#33A001',
        fontWeight: '600',
    },
    errorCard: {
        backgroundColor: '#ffebee',
        borderColor: '#ef5350',
    },
    errorText: {
        color: '#c62828',
        fontSize: 16,
        textAlign: 'center',
    },
    instructionCardUrgent: {
        backgroundColor: '#ffebee',
        borderWidth: 2,
        borderColor: '#ef5350',
    },
    
    instructionText: {
        paddingTop: 35,
        fontSize: 25,
        textAlign: 'center',
        color: '#33A001',
        fontWeight: '600',
    },
});

export default styles;