import { StyleSheet } from 'react-native';
import {Dimensions} from 'react-native'; 
const { height } = Dimensions.get('window');

const RouteGenerationStyles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#33A001',  // Ensure the background is clean
        flexDirection: 'column',
    },
    mapContainer: {
        flex: 1,  // Take up available space for the map
        marginBottom: 0,  // Add some space between the map and the form
    },
    toggleShelterContainer:{
        backgroundColor: '#33A001',
        borderColor: '#1C5900',
        borderWidth: 2,
        borderRadius: 15,
        position: 'absolute',
        top: 0.085*height,
        right: '3%',
        height: 0.04*height,
        width: '59%',
        flexDirection: 'row',
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    formContainer: {
        flex: 0.1,
        backgroundColor: "#33A001",
        paddingHorizontal: 15,
        borderTopLeftRadius: 20,
        borderTopRightRadius: 20,
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: -30,
        bottom: 0,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.8,
        shadowRadius: 7,
        position: 'relative'
    },
    input: {
        height: 40,
        borderColor: 'gray',
        borderWidth: 1,
        marginBottom: 15,
        paddingHorizontal: 8, 
        backgroundColor: "white",
        borderRadius: 8,
        width: '90%',
    },
    text: {
        color: "white",
        fontSize: 14, 
        textAlign: 'center',
    },
    buttonText: {
        color: 'white',
        fontSize: 20,
        flexWrap: 'wrap',
        textAlign: 'center',
    },
    button: {
        backgroundColor: "#267600",
        borderRadius: 20,
        paddingVertical: 8,
        paddingHorizontal: 20,
        justifyContent: 'center',
        alignItems: 'center',
        width: '50%',
        borderColor: 'white',
        borderWidth: 3,
    },
    generateRouteButton: {
        backgroundColor: "#33A001",
        borderRadius: 20,
        justifyContent: 'center',
        alignItems: 'center',
        width: '75%',
        height: '60%',
        borderWidth: 4,
        borderColor: 'white',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.8,
        shadowRadius: 7,
        flex: 1,
    },
    distanceDisplayContainter: {
        backgroundColor: "#33A001",
        borderRadius: 10,
        justifyContent: 'center',
        alignItems: 'center',
        position: 'absolute',
        top: 200,
        left: '37%',
        width: '26%',
        height: '8%',
        borderColor: 'white',
        borderWidth: 1,
    },
    distanceText: {
        color: "white",
        fontSize: 15,
    },
    fontText: {
        color: "#65CB37",
        fontSize: 20, 
        textAlign: 'center',
    },
    selectRouteButton: {
        backgroundColor: "#33A001",
        borderRadius: 20,
        justifyContent: 'center',
        alignItems: 'center',
        width: '75%',
        height: '60%',
        borderWidth: 4,
        borderColor: 'white',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.8,
        shadowRadius: 7,
        flex: 1,
    },
    dropdown: {
        height: 40,
        borderColor: 'gray',
        borderWidth: 1,
        marginBottom: 15,
        paddingHorizontal: 8,
        backgroundColor: "white",
        borderRadius: 8,
        width: '90%',
        justifyContent: 'center',
        zIndex: 10
    },
    // dropdownList: {
    //     height: '100%',
    //     borderColor: 'gray',
    //     borderWidth: 1,
    //     marginBottom: 15,
    //     paddingHorizontal: 8,
    //     backgroundColor: "white",
    //     borderRadius: 8,
    //     width: '70%',
    //     position: 'absolute',
    // },
    landmarkText: {
        marginVertical: 5,
    },
    routeNumberRow: {
        position: 'absolute',
        bottom: '26%',
        width: '100%',
        flexDirection: 'row',
        flex: 1,
        justifyContent: 'space-around',
    },
    routeNumberButton: {
        backgroundColor: '#487532',
        height: 40,
        width: 40,
        borderRadius: 20,
        justifyContent: 'center',
        alignItems: 'center',
        borderColor: 'white',
        borderWidth: 2,
    },
    routeNumberText: {
        color: '#B5B5B5',
        fontSize: 25,
    },
    dropdownListContainer: {
        zIndex: 10, // Ensure the dropdown is above other elements
        width: '90%'
      },
      dropdownList: {
        borderColor: '#1C5900',
        borderWidth: 1,
        borderRadius: 8,
        backgroundColor: 'white',
        maxHeight: 200,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.5,
        shadowRadius: 5,
        position: 'absolute',
        width: '90%'
      },
      dropdownItem: {
        paddingVertical: 10,
        paddingHorizontal: 15,
      },
      dropdownItemText: {
        color: '#333',
        fontSize: 16,
      },
      distanceInputContainer: {
          flexDirection: 'row',
          alignItems: 'center',
          borderBottomWidth: 1,
          borderColor: '#FFFFFF',
          paddingBottom: 5,
          marginBottom: 20,
          width: '70%',
      },
      shelteredLegend: {
        position: 'absolute',
        right: '5%',
        top: '8%',
        backgroundColor: '#FFFFFF',
        borderColor: '#1D5A00',
        borderWidth: 3,
        borderRadius: 10,
        width: '50%',
        height: '8%',
        justifyContent: 'center',
        alignItems: 'flex-end',
      }
});

export default RouteGenerationStyles;