import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: 'white',
    },
    map: {
        flex: 1,
        width: '100%',
    },
    whiteBackgroundCell: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        height: '40%',
        backgroundColor: 'white',
        borderTopLeftRadius: 30,
        borderTopRightRadius: 30,
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: -3,
        },
        shadowOpacity: 0.25,
        shadowRadius: 5,
        elevation: 5,
    },
    summaryCard: {
        position: 'absolute',
        alignSelf: 'center',
        top: '45%',
        backgroundColor: '#33A001',
        borderRadius: 25,
        paddingVertical: 15,
        paddingHorizontal: 20,
        width: '80%',
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 4,
        },
        shadowOpacity: 0.3,
        shadowRadius: 5,
        elevation: 8,
    },
    title: {
        color: 'white',
        fontSize: 48,
        fontWeight: 'bold',
        fontStyle: 'italic',
        textAlign: 'center',
        marginBottom: 10,
        textShadowColor: '#7FFF4D',
        textShadowOffset: {
            width: 2,
            height: 2,
        },
        textShadowRadius: 1,
        includeFontPadding: false,
        lineHeight: 48,
    },
    dataContainer: {
        width: '100%',
        alignItems: 'center',
        gap: 8,
    },
    dataSection: {
        alignItems: 'center',
        marginVertical: 2,
    },
    label: {
        color: 'white',
        fontSize: 20,
        fontWeight: '500',
        marginBottom: 0,
        lineHeight: 24,
    },
    valueContainer: {
        flexDirection: 'row',
        alignItems: 'baseline',
        justifyContent: 'center',
        marginTop: -4,
    },
    value: {
        color: 'white',
        fontSize: 64,
        fontWeight: 'bold',
        fontStyle: 'italic',
        includeFontPadding: false,
        textAlign: 'center',
        lineHeight: 70,
    },
    unit: {
        color: 'white',
        fontSize: 20,
        marginLeft: 5,
        alignSelf: 'flex-end',
        paddingBottom: 10,
    },
    unitLabel: {
        color: 'white',
        fontSize: 16,
        marginTop: -8,
        lineHeight: 16,
    },
    button: {
        position: 'absolute',
        bottom: 40,
        alignSelf: 'center',
        backgroundColor: '#1B5500',
        paddingVertical: 12,
        paddingHorizontal: 30,
        borderRadius: 30,
        width: '60%',
        alignItems: 'center',
        borderWidth: 3,
        borderColor: 'white',
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
    },
    buttonText: {
        color: 'white',
        fontSize: 24,
        textAlign: 'center',
        lineHeight: 28,
    },
});

export default styles;